### ISSUE TITLE
Ask about the reason for choosing running the functions of proActiv in docker container

### ISSUE THREAD

**Issue by CuteGold0407** [NaotoKubota/Kubota_puQTL#1]
Hi, 

Sorry to disturb！I notice you run the proActiv in 
the docker container, would you like to share about why? why not run the command directly by R on linux?
I decided to install the proActiv package under R environment on the linux, but it seemed very difficult because the downloading always failed. I wonder if you had the similar problem then. So maybe the docker container provides all the dependencies and thus it can successfully run？Sorry I am a freshman in this field, so my question may sounds very confusing.

Any reply is appreciated!

Best wishes

Jeep li

**Comment by NaotoKubota** [comment]
Hi Jeep,

As you mentioned, downloading software including proActiv often fails. I made a docker container because I wanted an environment that enables stable execution of proActiv in any machine such as my laptop, clusters, or any HPC. You can execute proActiv in a docker container like below:

```bash
$ docker pull naotokubota/proactiv:1.1.18
$ docker run --rm -it naotokubota/proactiv:1.1.18
R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(proActiv)

Attaching package: 'proActiv'

The following object is masked from 'package:stats':

    filter
```

Please try docker if you have still any problems in downloading proActiv.

Best,

**Comment by CuteGold0407** [comment]
Thanks very very much for your reply, which really solves my confusion! :)
